# Generated by Django 4.2.7 on 2023-11-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_number', '0003_alter_inputfield_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfield',
            name='label_alignment',
            field=models.CharField(choices=[('text-start', 'text-start'), ('text-center', 'text-center'), ('text-end', 'text-end')], max_length=20),
        ),
    ]
